### ISSUE TITLE
Query never resolves when the input is undefined

### ISSUE THREAD

**Issue by davbrito** [jsonnull/electron-trpc#144]
I'm consulting a query that does not have parameters this way:

`trpc.endpoint.useQuery(undefined);`

And it is never responding.

My current workaround is to send an empty object like this:

`
trpc.endpoint.useQuery({});`

**Comment by jsonnull** [comment]
Is the server expecting a value? Can you just not send it?

**Comment by davbrito** [comment]
I realized that it was my mistake. The query was being sent before the ipc was arttached on the main process.
