### ISSUE TITLE
Invalid mjs bundle: `contextBridge` shouldn't be imported in `main.mjs`

### ISSUE THREAD

**Issue by ylc395** [jsonnull/electron-trpc#180]
<img width="963" alt="image" src="https://github.com/jsonnull/electron-trpc/assets/12264626/2d1d87b8-f762-4096-896a-aac80e72dcd6">

`exposeElectronTRPC` import `contextBridge`, which is not available in main process. This cause a fatal error when users import `electron-trpc/main.mjs` in main process:

<img width="897" alt="image" src="https://github.com/jsonnull/electron-trpc/assets/12264626/6f4ba774-9208-42d0-b761-db4504569ad6">

**Comment by busybox11** [comment]
Have you found a solution? I'm having the same issue.
