### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by PavlMais** [jsonnull/electron-trpc#186]
I noticed there isn't any recent activity on this repository. 
Is there a chance this repository could be revived in the future, or are you perhaps looking for maintainers to help out? 
Thanks!

**Comment by mat-sz** [comment]
@PavlMais Hey, I'm maintaining a fork that fixes compatibility issues with TRPC 11.x, you might be interested in checking it out. https://github.com/mat-sz/trpc-electron

**Comment by jsonnull** [comment]
@PavlMais Sorry for the late reply, I've meant to get back into maintenance on this for a bit but a few things have kept me away.

I've finally gotten some bandwidth to be able to run the e2e tests locally and I'm catching up on things. Let me know if there's anything in particular you're looking for.
