### ISSUE TITLE
failed to resolve import "@trpc/client" and failed to resolve import "@trpc/server" 

### ISSUE THREAD

**Issue by LaiosOvO** [jsonnull/electron-trpc#203]
failed to resolve import "@trpc/client" and failed to resolve import "@trpc/server" 
![image](https://github.com/user-attachments/assets/129991a7-4698-4e20-9d86-8741d8ba6d38)
![image](https://github.com/user-attachments/assets/d2455915-b67c-40d6-95c3-32e836513fdb)
![image](https://github.com/user-attachments/assets/a74dfccb-5ef1-4529-9eb2-810f26db1d83)

**Comment by jsonnull** [comment]
Looks like you did not install the required TRPC packages for those imports: https://github.com/jsonnull/electron-trpc/blob/9b533d21f7e97f68ec9eaf3aba5d5df4db6f24be/examples/basic-react/package.json#L13-L15
